### ISSUE TITLE
`ValidationProps` interaction does not have the `.reply()` method

### ISSUE THREAD

**Issue by lassejlv** [underctrl-io/commandkit#46]
https://commandkit.js.org/guide/validation-file-setup then using the `ValidationProps`. Then if you use `interaction.reply(...)` it will throw an error. Version: `0.1.10`

**Comment by notunderctrl** [comment]
Hi. Can you please share the exact error you're facing. Thanks

**Comment by lassejlv** [comment]
When using ValidationProps type, and using .reply you are getting an type error.

**Comment by notunderctrl** [comment]
I was able to reproduce the issue:
```ts
import type { ValidationProps } from 'commandkit';

export default function ({ interaction, commandObj, handler }: ValidationProps) {    
    interaction.reply('This does not work.'); // Property 'reply' does not exist on type 'ChatInputCommandInteraction<CacheType> | ContextMenuCommandInteraction<CacheType> | AutocompleteInteraction<...>'.
}
```

### Reason
With version 1.10, validations also support [autocomplete](https://commandkit.js.org/guide/command-file-setup#autocomplete-function). This is a new feature in command files.

With this new update, the `interaction` object can now also be of type [`AutocompleteInteraction`](https://old.discordjs.dev/#/docs/discord.js/main/class/AutocompleteInteraction) alongside the previous [`ChatInputCommandInteraction`](https://old.discordjs.dev/#/docs/discord.js/main/class/ChatInputCommandInteraction) and [`ContextMenuCommandInteraction`](https://old.discordjs.dev/#/docs/discord.js/main/class/ContextMenuCommandInteraction).

### Fix
Since you can't "reply" to the [`AutocompleteInteraction`](https://old.discordjs.dev/#/docs/discord.js/main/class/AutocompleteInteraction) type (you can only "respond" with autocomplete), you need to add a check in your validation to ensure that the interaction type you're handling is of either [`ChatInputCommandInteraction`](https://old.discordjs.dev/#/docs/discord.js/main/class/ChatInputCommandInteraction), or [`ContextMenuCommandInteraction`](https://old.discordjs.dev/#/docs/discord.js/main/class/ContextMenuCommandInteraction).

```ts
import type { ValidationProps } from 'commandkit';

export default function ({ interaction, commandObj, handler }: ValidationProps) {
    if (interaction.isAutocomplete()) return;
    
    interaction.reply('This now works!');
}
```

**Comment by notunderctrl** [comment]
Gonna leave this open for now for feedback

**Comment by lassejlv** [comment]
Arr alright thanks for the help :) keep up the good work!
